Update clang-format configuration file
- add BeforeWhile: false
- the option is supported since v11.0 - using it before result with
  error: unknown key 'BeforeWhile'